### ISSUE TITLE
Implement assigned ViewModels

### ISSUE THREAD

**Issue by Pabluchenkoo** [ISIS3510-202410-Team11/Swift#13]
I left you the bare beginnings of MVVM. Preliminary implementation of landing view and signUp view

**Comment by CristianCaro915** [comment]
View models are nice, I have done mine !!

**Comment by CristianCaro915** [comment]
MVVM is OP, it uses Observabel pattern by default, crazyyy

**Comment by JuanSe2003** [comment]
In my case , I implement MVVM to my features and I try to use the Repository

**Comment by Pabluchenkoo** [comment]
I'm done with mines. Great teamwork
