### ISSUE TITLE
Documentation of architectural patterns

### ISSUE THREAD

**Issue by Pabluchenkoo** [ISIS3510-202410-Team11/Swift#15]

**Comment by CristianCaro915** [comment]
I do not know if singleton can be used, we have objs that are implemented once but they are not restricted to be created just once. Is an interface a use of singleton...

**Comment by JuanSe2003** [comment]
I justified the use of the Repository pattern and MVVM because the majority of the team made use of these two patterns.

**Comment by Pabluchenkoo** [comment]
Great work team !
