### ISSUE TITLE
FaceID research

### ISSUE THREAD

**Issue by Pabluchenkoo** [ISIS3510-202410-Team11/Swift#21]

**Comment by CristianCaro915** [comment]
How can you save someone's face.. what kind of file is it? This is a real challenge

**Comment by Pabluchenkoo** [comment]
You are right colleague! I'm on it!

**Comment by Pabluchenkoo** [comment]
> How can you save someone's face.. what kind of file is it? This is a real challenge

You are right colleague! I'm on it!

**Comment by Pabluchenkoo** [comment]
Research has come to an end. I've figured keychain is the right path!
