### ISSUE TITLE
Local Storage for vehicle Icons

### ISSUE THREAD

**Issue by Pabluchenkoo** [ISIS3510-202410-Team11/Swift#36]

**Comment by Pabluchenkoo** [comment]
Please guys @CristianCaro915 @JuanSe2003 give me some feedback. Let me know what else I can do!

**Comment by CristianCaro915** [comment]
Thanks my orc, you're the local storage CTO

**Comment by JuanSe2003** [comment]
I like the changes that you made @Pabluchenkoo for the Local Storage, and I like the images that you put

**Comment by Pabluchenkoo** [comment]
Thank u mates
